### ISSUE TITLE
Does integer type support values above 32 bits?

### ISSUE THREAD

**Issue by tevwildmus** [Vicyntae/SCV#1]
Hope I'm not intruding by creating issues here...

I started playing around with the latest beta, but haven't been able to use it successfully. It seems like it's initializing some (but not all) of the perks? I'm not certain on that yet, though.

Anyway, I got curious and started looking through the source to see if I could make heads or tails of anything. Bear in mind, I haven't done Skyrim development before, but this line stuck out to me:

https://github.com/Vicyntae/SCV/blob/6e6998ce15051f5af199236f87a463b7d194fcb0/Data/Scripts/Source/SCVLibrary.psc#L75

Typically when I see data types named 'int', I expect 32-bit signed integers by default, but 1,000,000,000,000 doesn't fall withing that range. Is this a bug, or are integer types in papyrus 64-bit?

**Comment by Vicyntae** [comment]
Honestly, I'm not sure. I'm just using that to avoid calling RandomInt too many times. However, whatever issues this may cause is is not related to the perks not initializing. I'm testing out a new format for perks and I think it has to do with the reference aliases starting up weird. I'll start looking at it now, decide if I should remove it.
