### ISSUE TITLE
Serpent Stone Vore ability activation 

### ISSUE THREAD

**Issue by ParabolicSamuel** [Vicyntae/SCV#5]
I can't seem to get the vore abilities to activate when touching the Serpent Stone.
I can activate the vore abilities from starting debug and make vore TRUE and they work fine.
I do have _Alternate Start_ if that makes a difference

**Rough list of steps taken**
1. Get to Serpent stone
2. Defeat guardian(s) - Ice Wrath(s)
3. Discover Serpent Stone
4. Activate Serpent Stone and get paralyze ability.
5. _?Vore ability activates?_ 

Am I missing something.

**Comment by Vicyntae** [comment]
I'll be honest, I have'nt tested the Serpent Stone extensively. I look into what happened.

**Comment by Vicyntae** [comment]
Okay, fixed. Added wisp around Serpent Stone to activate instead.
